In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('placement.csv')

In [5]:
df.columns

Index(['Unnamed: 0', 'cgpa', 'iq', 'placement'], dtype='object')

In [6]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [7]:
df

cgpa     iq  placement
0    6.8  123.0          1
1    5.9  106.0          0
2    5.3  121.0          0
3    7.4  132.0          1
4    5.8  142.0          0
..   ...    ...        ...
95   4.3  200.0          0
96   4.4   42.0          0
97   6.7  182.0          1
98   6.3  103.0          1
99   6.2  113.0          1

[100 rows x 3 columns]

In [13]:
X=df.iloc[:,:-1]
Y=df.iloc[:,2]


In [14]:
X

cgpa     iq
0    6.8  123.0
1    5.9  106.0
2    5.3  121.0
3    7.4  132.0
4    5.8  142.0
..   ...    ...
95   4.3  200.0
96   4.4   42.0
97   6.7  182.0
98   6.3  103.0
99   6.2  113.0

[100 rows x 2 columns]

In [15]:
Y

0     1
1     0
2     0
3     1
4     0
     ..
95    0
96    0
97    1
98    1
99    1
Name: placement, Length: 100, dtype: int64

In [17]:
#handling missing data 
df.isnull().value_counts()

cgpa   iq     placement
False  False  False        100
dtype: int64

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   cgpa       100 non-null    float64
 1   iq         100 non-null    float64
 2   placement  100 non-null    int64  
dtypes: float64(2), int64(1)
memory usage: 2.5 KB


In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.7,random_state=42)

In [21]:
X_train

cgpa     iq
79   6.5   90.0
41   5.4  114.0
58   8.0   79.0
48   6.6  138.0
98   6.3  103.0
57   6.5  130.0
75   4.8  169.0
32   7.0  139.0
94   4.7   52.0
59   4.8  112.0
63   6.3  128.0
84   5.7  169.0
37   8.1  149.0
29   7.0  112.0
1    5.9  106.0
52   7.0  175.0
21   7.1  151.0
2    5.3  121.0
23   4.7   87.0
87   5.7  132.0
91   7.5  158.0
74   6.7  154.0
86   5.1  128.0
82   6.5   37.0
20   6.6  120.0
60   6.9  139.0
71   6.1  132.0
14   6.1  103.0
92   5.2  110.0
51   4.8  141.0

In [22]:
X_test


cgpa     iq
83   7.5  130.0
53   8.3  168.0
70   6.3  127.0
45   6.0   66.0
44   7.5   61.0
..   ...    ...
67   5.0  118.0
46   5.3  114.0
68   4.0   75.0
61   7.3  137.0
97   6.7  182.0

[70 rows x 2 columns]

In [23]:
Y_train

79    1
41    0
58    1
48    1
98    1
57    1
75    0
32    1
94    0
59    0
63    1
84    0
37    1
29    1
1     0
52    1
21    1
2     0
23    0
87    1
91    1
74    1
86    0
82    1
20    1
60    1
71    1
14    0
92    0
51    0
Name: placement, dtype: int64

In [24]:
Y_test

83    1
53    1
70    1
45    1
44    1
     ..
67    0
46    0
68    0
61    1
97    1
Name: placement, Length: 70, dtype: int64

In [28]:
#feature scaling  It is a technique to standardize the independent variables 
#of the dataset in a specific range. In feature scaling, we put our variables in the same range 
#and in the same scale so that no any variable dominate the other variable.
from sklearn.preprocessing import StandardScaler  
st_x= StandardScaler()  
x_train= st_x.fit_transform(X_train)  
x_test= st_x.transform(X_test)  


In [29]:
x_train

array([[ 0.35337806, -1.02661339],
       [-0.80122353, -0.27082439],
       [ 1.92783477, -1.37301668],
       [ 0.45834184,  0.48496461],
       [ 0.1434505 , -0.61722768],
       [ 0.35337806,  0.23303494],
       [-1.43100621,  1.46119206],
       [ 0.87819696,  0.51645582],
       [-1.53596999, -2.2232793 ],
       [-1.43100621, -0.33380681],
       [ 0.1434505 ,  0.17005252],
       [-0.48633218,  1.46119206],
       [ 2.03279855,  0.8313679 ],
       [ 0.87819696, -0.33380681],
       [-0.27640462, -0.52275406],
       [ 0.87819696,  1.65013931],
       [ 0.98316075,  0.89435031],
       [-0.90618731, -0.05038593],
       [-1.53596999, -1.12108701],
       [-0.48633218,  0.29601736],
       [ 1.40301587,  1.11478877],
       [ 0.56330562,  0.98882394],
       [-1.11611487,  0.17005252],
       [ 0.35337806, -2.69564743],
       [ 0.45834184, -0.08187714],
       [ 0.77323318,  0.51645582],
       [-0.06647706,  0.29601736],
       [-0.06647706, -0.61722768],
       [-1.01115109,

In [30]:
x_test

array([[ 1.40301587,  0.23303494],
       [ 2.24272611,  1.42970085],
       [ 0.1434505 ,  0.13856132],
       [-0.17144084, -1.78240239],
       [ 1.40301587, -1.93985843],
       [-1.64093377,  0.73689427],
       [-1.32604243, -0.08187714],
       [-1.32604243,  2.31145469],
       [-0.17144084, -2.44371776],
       [ 0.6682694 ,  0.01259648],
       [-2.27071645, -0.71170131],
       [ 1.50797965,  0.17005252],
       [-1.32604243, -1.93985843],
       [-0.17144084,  0.8313679 ],
       [ 1.19308831, -1.15257822],
       [-0.3813684 ,  0.61092944],
       [-1.32604243,  1.02031515],
       [ 1.19308831, -2.28626172],
       [-0.80122353,  0.51645582],
       [-2.37568023, -0.42828043],
       [ 1.71790721, -0.27082439],
       [-1.85086133,  0.8313679 ],
       [ 0.87819696,  2.40592831],
       [ 1.50797965, -1.0581046 ],
       [ 2.45265367, -0.08187714],
       [-1.11611487,  1.68163052],
       [-1.32604243,  0.35899977],
       [-1.85086133, -2.53819139],
       [-1.11611487,

In [59]:
from sklearn.linear_model import LogisticRegression

In [52]:
clf = LogisticRegression()


In [54]:
clf.fit(x_train,Y_train)

LogisticRegression()

In [55]:
y_pred = clf.predict(x_test)

In [56]:
y_pred

array([1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1])

In [57]:
from sklearn.metrics import accuracy_score 

In [58]:
accuracy_score(Y_test,y_pred)

0.9142857142857143